define([], function () {
  return {
    NonOIMessage: 'This webpart cannot be added to a non-One Intranet site. This is not supported and will be removed without warning',
    AllDayEvent: 'All day',
    RecurrentEventLabel: 'Recurrent event',
    DeprecatedMessage: 'This webpart is no longer supported or updated. Please remove and add the card version of this webpart',
    ProfileTargetedHiddenMessage: 'This webpart is hidden for you because your profile does not satisfy {{function}}. The value of {{property}} in your profile is {{value}}.',
    ProfileTargetedNoTargetingOption: 'No targeting',
    ProfileTargetedPropertyPaneDescription: 'Use the filters below to show/hide the web part based on user profile properties',
    ProfileTargetedGroupName: '',
    ProfileTargetedPropertyFieldLabel: 'Property',
    ProfileTargetedOperatorFieldLabel: 'Operator',
    ProfileTargetedValueFieldLabel: 'Value',

    AlertDefatultLinkButton: 'Read more',
    AlertEditButton: 'Edit alert details',
    AlertDeleteButton: 'Delete alert',
    AlertDeleteConfirmation: 'Are you sure you wish to delete this alert?',

    AlertPanelDate: 'Date',
    AlertExpiredLabel: 'Expired',
    DisplayModeCardOption: 'Card',
    DisplayModeCardReducedOption: 'Card (Reduced thumbnail)',
    DisplayModeCompactCardOption: 'Compact card',
    DisplayModeStickerOption: 'Sticker',
    DisplayModeSlideOption: 'Slide',
    DisplayModeColorBlockOption: 'Color block',
    DisplayModeRowOption: 'Row',
    DisplayModeTextOverlapOption: 'Row text overlap',
    DisplayModeMinimalOption: 'Minimal',
    DisplayModeFreshOption: 'Fresh',
    DisplayModeFreshSimpleOption: 'Fresh simple',
    DisplayModeModernCardOption: 'Fresh',
    DisplayModeModernCardCompactOption: 'Fresh compact',
    DisplayModeTableOption: 'Table',

    ShareableDocumentCopyUrlConfirmation: 'Link copied to your clipboard',

    DocumentPickerFrameTitle: 'Select files from site picker view. Use the toolbar menu to perform operations.',
    DocumentPickerRecentTab: 'Recent documents',
    DocumentPickerExternalTab: 'External documents',
    DocumentPickerCurrentSiteTab: 'This site',
    DocumentPickerFollowingSitesTab: 'Following sites',
    DocumentPickerOrgAssetsLibrariesTab: 'Your organization',
    DocumentPickerStockImagesTab: 'Stock images',
    DocumentPickerAllSitesSitesTab: 'All sites',
    DocumentPickerExternalDocumentTextFieldLabel: 'Paste a link to a document',
    DocumentPickerNoRecentFilesMessage: 'No recent files found.',
    DocumentPickerTitle: 'Select a document',
    DocumentPikcerClearSelection: 'Clear selection',

    DocumentUploaderDragDropLabel: 'Drag and drop files here',
    DocumentUploaderChooseFilesLabel: 'Choose files to upload',
    DocumentUploaderUploadingFileError: 'Error uploading the document',
    DocumentUploaderOverwriteButton: 'Replace',
    DocumentUploaderOpenLocationButton: 'Open file location',
    DocumentUploaderOrLabel: 'or',
    DocumentUploaderNotAllowedExtension: 'File extension not allowed',
    DocumentUploaderDuplicateFileError: 'A file with this name already exists. Would you like to replace the existing one?',

    EventDateLabel: 'Event date',
    EventLocationLabel: 'Event location',
    EventScheduleHeader: 'Schedule',
    EventTagsHeader: 'Tags',
    EventLocationHeader: 'Location',
    EventStartDateLabel: 'Starts',
    EventEndDateLabel: 'Ends',
    EventsContactLabel: 'Main contact',
    EventsAddToCalendarLink: 'Add to calendar',
    EventOnlineMeeting: 'Online meeting',
    AllDayEvent: 'All day',

    FieldsPickerSettingsHeader: '{{fieldname}} field settings',
    FieldsPickerWithLabel: 'Width',
    FieldsPickerWidthSmallLabel: 'Small',
    FieldsPickerWidthMediumLabel: 'Medium',
    FieldsPickerWidthLargeLabel: 'Large',
    FieldsPickerWidthLargerLabel: 'Larger',
    FieldsPickerMoveUpButton: 'Move field up',
    FieldsPickerMoveDownButton: 'Move field down',
    FieldsPickerLoadingMessage: 'Loading fields...',
    FieldsPickerErrorMessage: 'Error loading the fields',
    FieldsPickerNoDataMessage: 'No fields found',

    FilterBuilderAddGroupButton: 'Group selected filters',
    FilterBuilderAddFilterButton: 'Add new clause',
    FilterBuilderValueTableHeader: 'Value',
    FilterBuilderOperatorTableHeader: 'Operator',
    FilterBuilderFieldTableHeader: 'Field',
    FilterBuilderLogicalTableHeader: 'And/Or',
    FilterBuilderAuthorOption: 'Author',
    FilterBuilderEditorOption: 'Modified by',
    FilterBuilderProjectsOption: 'Past projects',
    FilterBuilderResponsibilitiesOption: 'Responsibilities',
    FilterBuilderSkillsOption: 'Skills',
    FilterBuilderInterestsOption: 'Interests',
    FilterBuilderManagerOption: 'Manager',
    FilterBuilderJobOption: 'Job title',
    FilterBuilderDisplayNameOption: 'Display name',
    FilterBuilderDepartmentOption: 'Department',
    FilterBuilderLocationOption: 'Location',
    FilterBuilderFreshSiteTypeOption: 'Type of site',
    FilterBuilderFreshInstanceOption: 'Instance',
    FilterBuilderUserProjectsOption: 'User past projects',
    FilterBuilderUserInterestsOption: 'User interests',
    FilterBuilderUserSkillsOption: 'User skills',
    FilterBuilderUserManagerOption: 'User manager',
    FilterBuilderUserJobOption: 'User job title',
    FilterBuilderUserAccountOption: 'User account',
    FilterBuilderUserNameOption: 'User name',
    FilterBuilderUserDepartmentOption: 'User department',
    FilterBuilderUserDepartmentChildrenOption: 'User department (and children)',
    FilterBuilderUserLocationOption: 'User location',
    FilterBuilderUserLocationChildrenOption: 'User location (and children)',
    FilterBuilderIDWithChildrenOption: 'and children',
    FilterBuilderNameOption: 'name',
    FilterBuilderNewFilerButton: 'Insert new filter above',
    FilterBuilderRemoveFilerButton: 'Remove this filter',
    FilterBuilderManagePropertyLabel: 'Select or type a property',
    FilterBuilderValueLabel: 'Select or type a value',
    FilterBuilderOperatorLabel: 'Select the operator',
    FilterBuilderOperatorContainsLabel: 'contains',
    FilterBuilderOperatorEqualsLabel: 'equals',
    FilterBuilderOperatorLessThanLabel: 'less than',
    FilterBuilderOperatorGreaterThanLabel: 'greater than',
    FilterBuilderOperatorLessOrEqualsLabel: 'less or equals',
    FilterBuilderOperatorGreaterOrEqualsLabel: 'greater or equals',
    FilterBuilderOperatorNotEqualsLabel: 'not equals',
    FilterBuilderOperatorTermLabel: 'equals and children',
    FilterBuilderFieldMandatoryError: 'This field is mandatory',
    FilterBuilderInvalidCharactersError: 'Invalid characters',
    FilterBuilderCheckbox: 'Select filter for grouping',

    HierarchicalSiteRemoveFilterButton: 'Remove filter',
    HierarchicalSiteApplyFilterButton: 'Apply filter',
    IconPickerDialogTitle: 'Choose an icon',
    IconPickerChooseButton: 'Choose',
    IconPickerDialogDescription: 'Use the search box to help you to find your icon.',
    IconPickerLabel: 'Icon',
    IconPickerSearchBoxLabel: 'Search icons',

    KeywordsSuggestionsHeaderText: 'Suggested keywords',
    KeywordsMostRecentlyUsedHeaderText: 'Suggested keywords',
    KeywordsLoadingText: 'Loading',
    KeywordsNoResultsFoundText: 'No results found',
    KeywordsSuggestionsAvailableAlertText: 'Keywords picker suggestions available',
    KeywordsSuggestionsContainerAriaLabel: 'Suggested keywords',
    KeyWordPickerFieldLabel: 'Pick a term',

    MeetTheTeamAnswerLabel: 'Answer',
    MeetTheTeamQuestionLabel: 'Question',

    SearchResultsPickerErrorMessage: 'Error loading the items',
    SearchResultsPickerNoDataMessage: 'No items found',
    SearchResultsPickerLoadingMessage: 'Loading items...',
    SearchResultsPickerLabel: 'Click in the cards to select/unselect the items',
    SearchResultsPickerSelectedCountLabel: 'items selected',
    SearchResultsPickerSearchBoxLabel: 'Search items',
    SearchResultsPickerChooseButton: 'Choose',
    SearchResultsPickerDeleteButton: 'Delete',
    SearchResultsPickerHeader: 'Select the items',

    PostPickerSelectedCountLabel: '{{n}} posts',
    PostPickerCheckbox: 'Select post',
    PostPickerSelectAllCheckbox: 'Toggle selection for all items',
    PostPickerHeader: 'Select the posts to display',
    PostPickerGroupPlaceholder: 'Select a group',
    PostPickerGroupLabel: 'Group',
    PostPickerSearchLabel: 'Type keyword or paste the URL of the post',
    PostPickerUrlLabel: 'Paste the URL of the post',
    PostPickerEmptyStateMessage: 'Select a group to see the posts or paste the URL of the post in the text field',
    PostPickerGroupImageAlt: 'group image',
    PostPickerGroupsError: 'Error loading groups.',
    PostPickerPostError: 'Error loading posts.',
    PostPickerPostNotFoundError: 'The post cannot be found.',
    PostPickerPostColumn: 'Post',
    PostPickerAuthorColumn: 'Author',
    PostPickerCreatedColumn: 'Created',
    PostPickerURLColumn: 'URL',
    PostPickerIntroductionColumn: 'Intro',
    PostPickerIntroductionLabel: 'Introduction',
    PostPickerIntroductionDescription: 'This text will be displayed on top of the post.',
    PostPickerSaveAndSelectButton: 'Save and select',
    PostPickerOpenPostButton: 'Open post',
    PostPickerImageAlt: 'post image',
    PostPickerCreatedLabel: 'Created',

    PeopleLocationLabel: 'Location:',
    PeopleDepartmentLabel: 'Department:',

    PeoplePickerSuggestionsHeaderText: 'Suggested people',
    PeoplePickerMostRecentlyUsedHeaderText: 'Suggested contacts',
    PeoplePickerLoadingText: 'Loading',
    PeoplePickerNoResultsFoundText: 'No results found',
    PeoplePickerSuggestionsAvailableAlertText: 'People picker suggestions available',
    PeoplePickerSuggestionsContainerAriaLabel: 'Suggested contacts',

    PlaceholderText: 'Configure your web part',
    PlaceholderDescription: 'Please configure this web part.',

    ProvisioningFormSiteTypeLabel: 'What type of resource do you need?',
    ProvisioningFormSiteTypePlaceholder: 'Select an option',
    ProvisioningFormSiteNameLabel: 'Name',
    ProvisioningFormSiteUrlLabel: 'URL',
    ProvisioningFormSiteDescriptionLabel: 'Short description',
    ProvisioningFormRequestReasonLabel: 'Why do you need this?',
    ProvisioningFormTimeZoneLabel: 'Time zone',
    ProvisioningFormLocaleLabel: 'Locale',
    ProvisioningFormSiteOwnersLabel: 'Who are the owners of this site?',
    ProvisioningFormSiteMembersLabel: 'Who are the members of this site?',
    ProvisioningFormSiteVisitorsLabel: 'Who can view this site?',
    ProvisioningFormSitePrivateDescription: 'Only members can view the content and membership requires approval by a site owner.',
    ProvisioningFormSitePublicAllDescription: 'Everyone in your organization can see the content.',
    ProvisioningFormSiteOwnersDescription: 'The following group(s) will be added as owners:',
    ProvisioningFormSiteMembersDescription: 'The following group(s) will be added as members:',
    ProvisioningFormSiteVisitorsDescription: 'The following group(s) will be added as visitors:',
    ProvisioningFormGroupPublicDescription: 'Everyone in your organization can see the O365 group and join it without getting approval from the team owner.',
    ProvisioningFormLoadingSchemaLabel: 'Loading list schema',
    ProvisioningFormParentTermLabel: 'Select the parent taxonomy term',
    ProvisioningFormAddNavigationLabel: 'Add menu item in the global navigation',
    ProvisioningFormEnableExternalLabel: 'Enable external access',
    ProvisioningFormEnableAnalyticsLabel: 'Enable analytics',
    ProvisioningFormSentConfirmation: 'Your request has been successfully sent to:',
    ProvisioningFormSaveConfirmation: 'The request has been successfully saved.',
    ProvisioningFormSharingPrivateLabel: 'Private',
    ProvisioningFormSharingPublicLabel: 'Public',
    ProvisioningFormSharingHeader: 'Access and sharing',
    ProvisioningFormEntityDetailsHeader: '{{entity}} details',
    ProvisioningFormNoDataMessage: 'No collaboration site types found',
    ProvisioningFormLoadingMessage: 'Loading collaboration site types...',
    ProvisioningFormUpdatingError: 'Error updating the request',
    ProvisioningFormCreatingError: 'Error creating the request',
    ProvisioningUrlExistMessage: 'This URL is already in use. Please write a different one.',

    QueryBuilderUseAdvancedSearchLabel: 'Use advanced search',
    QueryBuilderQueryTextLabel: 'Search query',
    QueryBuilderRowLimitLabel: 'Number of results',
    QueryBuilderShowPagination: 'Show pagination',
    QueryBuilderResultsPerPage: 'Results per page',
    QueryBuilderScopeLabel: 'Scope',
    QueryBuilderPathLabel: 'Path',
    QueryBuilderSitesLabel: 'Sites',
    QueryBuilderSitesLabelPlaceholder: 'All sites',
    QueryBuilderLibraryLabel: 'Library',
    QueryBuilderLibraryPlaceholder: 'Select a library',
    QueryBuilderFolderLabel: 'Folder',
    QueryBuilderFolderPlaceholder: 'Select a folder',
    QueryBuilderContentTypeLabel: 'Content type',
    QueryBuilderContentTypePlaceholder: 'Select a content type',
    QueryBuilderContentTypeIdLabel: 'Content type (select from dropdown or enter ID)',
    QueryBuilderChannelLabel: 'Channel',
    QueryBuilderChannelPlaceholder: 'Select a channel',
    QueryBuilderActiveToggleLabel: 'Filter expired or unpublished',
    QueryBuilderTrimDuplicatesLabel: 'Filter duplicates',
    QueryBuilderAudienceToggleLabel: 'Enable audience targeting',
    QueryBuilderEnforcePagePropertyFilterLabel: 'Ensure at least one page property matches',
    QueryBuilderActiveEventsToggleLabel: 'Filter past events',
    QueryBuilderFeaturedToggleLabel: 'Featured only',
    QueryBuilderExtensionLabel: 'Extension',
    QueryBuilderExtensionPlaceholder: 'Select an extension',
    QueryBuilderSourceIdLabel: 'Source ID',
    QueryBuilderRefinementFiltersLabel: 'Refinement filters',
    QueryBuilderQueryTemplateDescription: 'The search query in KQL format. You can use search query variables.',
    QueryBuilderQueryTemplateLabel: 'Query template',
    QueryBuilderRefinementFiltersDescription: 'Specifies managed properties used as refiners (comma-separated).',
    QueryBuilderSortListDescription: 'Enter values with format [managed property]:[ascending|descending] (comma-separated). Example: LastModifiedTime:ascending,ViewsRecent:descending',
    QueryBuilderScopePlaceholder: 'Select an option',
    QueryBuilderEverythingOption: 'Everything',
    QueryBuilderCurrentSiteCollectionOption: 'Current site collection',
    QueryBuilderCurrentSiteOption: 'Current site',
    QueryBuilderSpecificPathOption: 'Specific path',
    QueryBuilderCurrentHubOption: 'Current hub',
    QueryBuilderAnyOption: '[any]',
    QueryBuilderSelectedHubsOption: 'Selected hubs',
    QueryBuilderOpenDialogButton: 'View more options',
    QueryBuilderAdvancedLabel: 'Use advanced properties',
    QueryBuilderAdvancedOnLabel: 'Advanced',
    QueryBuilderAdvancedOffLabel: 'Basic',
    QueryBuilderFiltersLabel: 'Additional filters',
    QueryBuilderPageTypePlaceHolder: 'Select page type',
    QueryBuilderPageTypeLabel: 'Select page type',
    QueryBuilderPageTypeNewsPagesLabel: 'News pages',
    QueryBuilderPageTypeSitePagesLabel: 'Site pages',
    QueryBuilderPageTypeAllPagesLabel: 'All',
    QueryBuilderMixedItemTypePlaceHolder: 'Select item type',
    QueryBuilderMixedItemTypeLabel: 'Select item type',
    QueryBuilderMixedLinksTypeLabel: 'Links',
    QueryBuilderMixedPagesTypeLabel: 'Pages',
    QueryBuilderMixedDocumentsTypeLabel: 'Documents',
    QueryBuilderSortListPlaceHolder: 'Select sort by',
    QueryBuilderSortListLabel: 'Sort by',
    QueryBuilderSortAlplabeticalLabel: 'Alphabetical (A-Z)',
    QueryBuilderSortCreatedLabel: 'Created (latest to oldest)',
    QueryBuilderSortModifiedLabel: 'Modified (latest to oldest)',
    QueryBuilderSortPublishedLabel: 'Published (latest to oldest)',
    QueryBuilderSortTrendingLabel: 'Trending (most viewed on top)',
    QueryBuilderSortLastNameLabel: 'Last name (A-Z)',
    QueryBuilderSortFirstNamelLabel: 'First name (A-Z)',
    QueryBuilderSortOrderLabel: 'Order (smaller to larger)',
    QueryBuilderSortStartDateLabel: 'Start date (earliest to latest)',
    QueryBuilderSortRankLabel: 'Ranking (most relevant on top)',
    QueryBuilderSortCreatedAscendingLabel: 'Created (oldest to latest)',
    QueryBuilderSortModifiedAscendingLabel: 'Modified (oldest to latest)',
    QueryBuilderSortReviewDateLabel: 'Review date (oldest to latest)',
    QueryBuilderSortContentOwnerLabel: 'Content owner (A-Z)',
    QueryBuilderSortViewCountLabel: 'Views (highest to lowest)',
    QueryBuilderSortViewCountAscendingLabel: 'Views (lowest to highest)',
    QueryBuilderSortRecentViewCountLabel: 'Recent views (highest to lowest)',
    QueryBuilderSortRecentViewCountAscendingLabel: 'Recent views (lowest to highest)',
    QueryBuilderSortViewerCountLabel: 'Unique views (highest to lowest)',
    QueryBuilderSortViewerCountAscendingLabel: 'Unique views (lowest to highest)',
    QueryBuilderSortManualLabel: 'Manual',
    QueryBuilderSortManualDescription: 'To change the order, use drag-and-drop or the "up" and "down" buttons next to each item',

    QueryBuilderHubsPlaceHolder: 'Select hub sites',
    QueryBuilderHubSitesLabel: 'Hub sites',
    QueryBuilderAlertTitle: 'You may lose your changes!',
    QueryBuilderAlertMessage: 'If you continue and go to the basic mode, you will lose the changes made in the query template',

    RefinerHeader: 'Refiners',
    RefinerShowLessButton: 'Show less',
    RefinerShowMoreButton: 'Show {{num}} more',
    RefinerAriaPrefix: 'Refiner',

    SearchBoxCharMessage: 'A minimum of {{num}} characters is required',

    TablePreviousResultsButton: 'Previous page of results',
    TableNextResultsButton: 'Next page of results',
    TableResultsCountLabel: 'About {{count}} results',
    TaxonomyPickerTitle: 'Select a term',

    TeamsPanelHeader: 'Chat in Teams',
    TeamsPanelNoChannelError: 'You cannot share in the {{teamname}} team because there are no channels in this team',
    TeamsPanelNoTeamsError: 'You cannot share in Teams because you have not yet joined any Team',
    TeamsPanelLoadingMessage: 'Loading your teams...',
    TeamsPanelCommentLabel: 'Add a comment',
    TeamsPanelChannelComboLabel: 'Select a channel',
    TeamsPanelTeamComboLabel: 'Select a Team',

    ToolAddFavoriteButton: 'Add to favorites',
    ToolRemoveFavoriteButton: 'Remove from favorites',
    ToolEditButton: 'Edit tool details',
    ToolDeleteButton: 'Delete tool',
    ToolDeleteConfirmation: 'Are you sure you wish to delete this tool?',

    ToolTabbedFavorites: 'Favorites',
    ToolTabbedFeatured: 'Featured',
    ToolAriaLabel: 'Tool',
    ToolDesktopOnlyLabel: 'Desktop only',
    ToolMobileOnlyLabel: 'Mobile only',
    MoreInformation: 'More information',
    ToolInformation: 'Information about this tool',

    YammerPanelHeader: 'Post in Yammer',
    YammerPanelPromptText: "What's going on?",

    // IDatePickerStrings
    DatePickerMonths: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    DatePickerShortMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    DatePickerDays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    DatePickerShortDays: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
    DatePickerGoToToday: 'Go to today',
    DatePickerPrevMonthAriaLabel: 'Go to previous month',
    DatePickerNextMonthAriaLabel: 'Go to next month',
    DatePickerPrevYearAriaLabel: 'Go to previous year',
    DatePickerNextYearAriaLabel: 'Go to next year',
    DatePickerIsRequiredErrorMessage: 'This date is required.',
    DatePickerInvalidInputErrorMessage: 'Invalid date format.',

    DatePickerFromDatePlaceholder: 'Start date',
    DatePickerToDatePlaceholder: 'End date',

    DateHelperTodayLabel: 'Today',
    DateHelperYesterdayLabel: 'Yesterday',
    DateHelperTomorrowLabel: 'Tomorrow',
    DateHelperInHoursLabel: 'In {{time}} hours',
    DateHelperInMinutesLabel: 'In {{time}} minutes',
    DateHelperInLess5MinutesLabel: 'In less than 5 minutes',
    DateHelperDaysAgoLabel: '{{days}} days ago',
    DateHelperHoursAgoLabel: '{{time}} hours ago',
    DateHelperMinutesAgoLabel: '{{time}} minutes ago',
    DateHelperLess5MinutesAgoLabel: 'Less than 5 minutes ago',
    DateHelperDateTimeSeparatorLabel: 'at',

    // Events calendar strings
    EventsCalendarNextLabel: 'Next',
    EventsCalendarBackLabel: 'Back',
    EventsCalendarTodayLabel: 'Today',

    //Validation messages
    ValidatorHelperExtensionMessage: 'This file extension is not allowed',
    ValidatorHelperSortListMessage: 'This is not a valid sort list',
    ValidatorHelperGuidMessage: 'This is not a valid guid',
    ValidatorHelperNumberMessage: 'This is not a valid number',
    ValidatorHelperUrlMessage: 'This is not a valid url',
    ValidatorHelperRequiredMessage: 'This field is required',
    ValidatorHelperCodeMessage: 'This is not a valid code',

    //Refiners
    DepartmentRefinerLabel: 'Department',
    BaseOfficeLocationRefinerLabel: 'City',
    FreshOfficeNumberRefinerLabel: 'City',
    JobTitleRefinerLabel: 'Job title',
    PeopleKeywordsRefinerLabel: 'Skills and interests',
    FreshArticleDate: 'Publish date',
    FreshClientRefinerLabel: 'Client',
    FreshProjectManagerRefinerLabel: 'Project manager',
    FreshProjectStartDateRefinerLabel: 'Start date',
    FreshProjectEndDateRefinerLabel: 'Estimated end date',
    FreshRagStatusRefinerLabel: 'RAG status',
    FreshProjectPriorityRefinerLabel: 'Priority',
    FreshProjectStatusRefinerLabel: 'Project stage',
    FreshArticleDateRefinerLabel: 'Publish date',
    FreshSiteTypeRefinerLabel: 'Site type',
    FreshInstanceRefinerLabel: 'Instance',
    FreshToolsCategoryRefinerLabel: 'Tools category',
    DisplayAuthorRefinerLabel: 'Author',
    CreatedRefinerLabel: 'Created',
    LastModifiedTimeRefinerLabel: 'Modified',
    categoryRefinerLabel: 'Category',
    FileExtensionRefinerLabel: 'File extension',
    FreshSortableSiteTitleRefinerLabel: 'Site',
    RefinersAllOption: 'All',
    RefinerDateLaterLabel: '{tokenFrom} or later',
    RefinerDateBeforeLabel: 'Before {tokenTo}',
    RefinerDateFromToLabel: 'From {tokenFrom} up to {tokenTo}',
    RefinerDateMinOrLaterLabel: 'Anytime',

    //ColourPicker
    ColorPickerNoColorLabel: 'Transparent',
    ColorPickerLessColorsLabel: 'Fewer colors',
    ColorPickerMoreColorsLabel: 'More colors',
    ColorPickerThisSiteLabel: 'Choose a color from this site',
    ColorPickerOtherColourLabel: 'Choose a standard color',

    ColorPrimaryLabel: 'Smalt', //'Primary',            #00338d
    ColorSecondaryLabel: 'Persian blue', //'Secondary',          #1e49e2
    ColorTertiaryLabel: 'Persian blue', //'Tertiary',           #1e49e2
    ColorAccentLabel: 'Smalt', //'Accent',             #00338d
    ColorLightLabel: 'Cold purple', //'Light',              #9ab3dd
    ColorLighterLabel: 'Spindle', //'Lighter',            #c7d5ed
    ColorLighterAltLabel: 'Black squeeze', //'Lighter alternative',#f0f4fa
    ColorDarkLabel: 'Midnight blue', //'Dark',               #00276b

    ColorBlackLabel: 'Nile blue', //'Black',                      #183453
    ColorNeutralDarkLabel: 'San juan', //'Neutral dark',               #274668
    ColorNeutralPrimaryLabel: 'Blue zodiac', //'Neutral primary',            #0c233c
    ColorNeutralPrimaryAltLabel: 'Kashmir blue', //'Neutral primary alternative',#517192
    ColorNeutralSecondaryLabel: 'Bermuda gray', //'Neutral secondary',          #6b89a8
    ColorNeutralTertiaryLabel: 'Nepal', //'Neutral tertiary',           #8aa3bd

    ColorNeutralTertiaryAltLabel: 'Cloud', //'Neutral tertiary alternative',   #c8c6c4
    ColorNeutralQuaternaryLabel: 'Alto', //'Neutral quaternary',             #d0d0d0
    ColorNeutralQuaternaryAltLabel: 'Wester', //'Neutral quaternary alternative', #e1dfdd
    ColorNeutralLightLabel: 'Ebb', //'Neutral light',                  #edebe9
    ColorNeutralLighterLabel: 'Desert storm', //'Neutral lighter',                #f3f2f1
    ColorNeutralLighterAltLabel: 'Pampas', //'Neutral lighter alternative',    #faf9f8
    ColorWhiteLabel: 'White', //'White',                          #ffffff

    // profile component labels
    ProfileProgress: '{{progress}}% complete',
    AriaAlertText: 'A Coachmark has appeared',
    AriaDescribedByText: 'Press enter or alt + C to open the Coachmark notification',
    AriaLabelledByText: 'Coachmark notification',
    ViewProfile: 'View profile',
    MissingFieldsText: 'The following field(s) are missing: ',
    DefaultExternalEditorButtonText: 'Edit profile',

    SiteOwnerLabel: 'Site owner',
    NumFilesLabel: 'Number of files',
    AccessCountLabel: 'Access count (all time)',
    AccessCount7Label: 'Access count (last 7 days)',
    LastModifiedLabel: 'Last modified',
    CreatedLabel: 'Created',

    NoMembersLabel: 'Number of members',
    NoChannelsLabel: 'Number of channels',
    LastMessageLabel: 'Last message',

    CategoriesPivotLabel: 'Select a category',

    //Datasource
    EditConfigurationLabel: 'Edit datasource',
    NewConfigurationLabel: 'New datasource',

    DatasourceTextLabel: 'Name',
    DatasourceIconLabel: 'Icon',
    DatasourceEndpointTypeLabel: 'Endpoint type',
    DatasourceEndpointLabel: 'Endpoint',
    DatasourceEndpointMessage: 'You may want to use a proxy to avoid CORs issues',
    DatasourcePathToDataLabel: 'Path to data',
    DatasourcePathToTitleLabel: 'Path to title',
    DatasourcePathToUrlLabel: 'Path to URL',
    DatasourceSeeMoreLinkUrlLabel: 'URL of the link to see more items',
    DatasourceSeeMoreLinkTextLabel: 'Text of the link to see more items',
    DatasourcePathToDescriptionLabel: 'Path to description',
    DatasourcePathToDateLabel: 'Path to date',
    DatasourcePathToImageLabel: 'Path to image or icon',
    DatasourcePathToColorLabel: 'Path to color',
    DatasourcePathToTitleHeaderLabel: 'Table title column header',
    DatasourcePathToDescriptionHeaderLabel: 'Table description column header',
    DatasourcePathToDateHeaderLabel: 'Table date column header',

    DatasourceEndpointSharePointOption: 'SharePoint',
    DatasourceEndpointSearchOption: 'Search',
    DatasourceEndpointGraphOption: 'Graph',
    DatasourceEndpointRssOption: 'RSS',
    DatasourceEndpointGenericOption: 'Generic',

    // Bookmarks
    BookmarksHeader: 'Personal bookmarks',
    AddBookmarkButton: 'Add bookmark',
    DeleteBookmarkButton: 'Delete bookmark',
    EditBookmarkButton: 'Edit bookmark',
    ManageBookmarksButton: 'Manage',
    BookmarkTitleLabel: 'Title',
    BookmarkUrlLabel: 'URL',
    BookmarkTitleDescription: 'Enter a short title or description for the bookmark',
    BookmarkUrlDescription: 'Enter the full URL of the bookmark',
    TitleValidationMessage: 'Title cannot be blank',
    UrlValidationMessage: 'URL cannot be blank',
    BookmarkAddedMessage: 'Bookmark added',
    BookmarkUpdatedMessage: 'Bookmark updated',
    BookmarkDeletedMessage: 'Bookmark deleted',
    BookmarkAddFailureMessage: 'Failed to add bookmark. You have reached the item limit. Try shortening your title(s) or removing some old bookmarks.',
    BookmarkMoveUpMessage: 'Move bookmark up',
    BookmarkMoveDownMessage: 'Move bookmark down',

    SearchableDropdownPlaceholder: 'Search an option',

    UnsupportedBrowser: 'This feature is not supported in IE11 or legacy Edge. Please refer to your IT department for a modern web browser.',

    //CardLists
    NoResultsMessage: 'No items available',

    // MGT Components
    // Person card
    BadgesHeading: 'Badges',
    BadgeRecipientsHeading: 'People with this badge:',
    NoUsersWithBadge: 'Nobody has earned this badge yet',

    // LinkPicker
    LinkPickerTitleLabel: 'Link title',
    LinkPickerUrlLabel: 'Link URL',
    LinkPickerDescriptionLabel: 'Link description',
    LinkPickerIconLabel: 'Icon',
    LinkPickerImageUrlLabel: 'Image URL',
    LinkPickerImageUrlDescription: 'Enter a valid image URL. If left blank, a default icon will be provided',
    LinkPickerDisplayTypeLabel: 'Display Type',
    displayTypeAcronym: 'Acronym',
    displayTypeIcon: 'Icon',
    displayTypeImage: 'Image',
    LinkPickerShowIconLabel: 'Show icon',
    LinkPickerToggleAcronymLabel: 'Show acronym over image',
    LinkPickerToggleAcronymOnText: 'Show acronym',
    LinkPickerToggleAcronymOffText: 'Hide acronym',

    // kudos
    GiveKudos: 'Give kudos',

    //Rich editor
    EditorDocumentPickerOption: 'Pick a document',
    EditorPagePickerOption: 'Pick a page',
    EditorLinkDialogTitle: 'Edit link',
    EditorLinkTextLabel: 'Text to display',
    EditorLinkAddressLabel: 'Address',
    EditorLinkBrowseButton: 'Browse',
    EditorInvalidUrlMessage: 'This is not a valid url',

    // Form
    RecipientLabel: 'Recipient',
    RecipientDescription: 'Who are you praising? You can select multiple people',
    TitleLabel: 'Title',
    TitleDescription: 'Give a brief sentence to describe why you are giving praise',
    DescriptionLabel: 'Description',
    DescriptionDescription: 'If you wish, you can provide more detail about why you are giving praise',
    IconLabel: 'Icon',
    IconDescription: 'Choose a relevant icon',
    BackgroundColorLabel: 'Color',

    CreateButton: 'Create',
    CancelButton: 'Cancel',
    RefreshButton: 'Refresh',
    RefreshText: 'Refresh this page',

    TermPickerDefaultPlaceHolder: 'Type term to tag',
    TermPickerTreeTitle: 'Select one or more tags',
    TermPickerAddTagButtonTooltip: 'Add Tag',
    TermPickerApplyButtonText: 'Apply',
    TermPickerCancelButtonText: 'Cancel',
    TermPickerLoadMoreText: 'Load more',
    TermPickerRemoveButtonText: 'Remove',
    TermPickerPanelCloseButtonText: 'Close',
    TermPickerNoResultsFound: 'No results found',
    TermPickerSuggestionInLabel: 'in',
    TermPickerExpandButonAriaLabel: 'Expand/collapse group',

    //Group Explorer
    GroupExplorerGroupSecurity: 'Security group',
    GroupExplorerGroupMS365: 'Microsoft 365',
    GroupExplorerGroupDistribution: 'Distribution list',
    GroupExplorerGroupMailSecurity: 'Mail-enabled security',

    DeleteDialogConfirmation: 'Are you sure you wish to delete this item?',

    FocalPointImageAlt: 'Image where the focal point is set',
    FocalPointDescription: 'Click the image to set the focal point',

    RichTextEditorAriaLabel: 'Text editor',
    // Conversation Viewer
    ViewConversation: 'View conversation',

    Selected: 'Selected',

    //Search
    SearchScopeLabel: 'Scope',
    SearchBoxClearButton: 'Clear',
    SearchModifiedByYouLabel: 'Modified by you',
    SearchAccessedByYouLabel: 'Opened by you',
    SearchVisitedByYouLabel: 'Visited by you',
    SearchContainerPrepositionLabel: 'in',
    SearchCreatedByLabel: 'Created by',
    SearchModifiedByLabel: 'Modified by',
    SearchDeleteFromHistory: 'Delete',
    SearchBoxPlaceholder: 'Search...',
    SearchNoResultsMessage: 'No results found',

    SearchSpellingCorrectionLabel: 'Did you mean {{1}}?',
    SearchMinimumCharacterMessage: 'A minimum of 3 characters is required. Then press Enter to update the results',
    SearchScopesHeader: 'Scope of the search',
    SearchPagesAndDocumentsHeader: 'Pages and documents',
    SearchRecentSitesHeader: 'Visited sites',
    SearchTrendingItemsHeader: 'Trending items',
    SearchHistoryHeader: 'Your private search history',
    SearchPeopleHeader: 'People',
    SearchSitesHeader: 'Sites',
    SearchOtherHeader: 'Other',
    SearchBookmarkHeader: 'Bookmark',
    SearchPromotedContentHeader: 'Promoted content',

    SearchScopeNameOrganization: 'Organization',
    SearchScopeNameReferringHub: 'Referring hub (when exists)',
    SearchScopeNameReferringHubExists: 'Referring hub',
    SearchScopeNameThisHub: 'This hub',
    SearchScopeNameReferringSite: 'Referring site',
    SearchScopeNameThisSite: 'This site',
    SearchScopeNameCustom: 'Custom',

    SearchErrorIntroduction: 'Sorry, we are currently experiencing problems retrieving this content.',
    SearchErrorReasonsTitle: 'If possible, please try again later or try following these steps:',
    SearchErrorReasonOne: 'The search server is temporarily unavailable.',
    SearchErrorReasonTwo: 'There is a problem with your search query.',
    SearchErrorReasonThree: 'There is a problem with your network connection.',
    SearchErrorSolutionsTitle: 'What you can do:',
    SearchErrorSolutionOne: 'Check your network connection.',
    SearchErrorSolutionTwo: 'Close and re-launch your browser.',
    SearchErrorSolutionThree: 'Restart your laptop.',
    SearchErrorSolutionFour: 'Use the refresh button.',
    SearchErrorContact: 'If the problem persists, contact your member firm help desk for assistance',
    SearchErrorSignature: 'Thank you for your patience.',
    SearchErrorTryAgain: 'To try again, use the refresh button:',

    TopicExplorerTopicOwner: 'Topic owner',
    TopicExplorerOpenSearch: 'Open search',

    // LocalizationHelper
    NoResultsFound: 'No results found',
    // LocalizationHelper - Person card component
    SendEmailLinkSubtitle: 'Send email',
    StartChatLinkSubtitle: 'Start chat',
    ShowMoreSectionButton: 'Show more',
    // LocalizationHelper - Person card contact component
    ContactSectionTitle: 'Contact',
    // LocalizationHelper - Person card organization component
    ReportsToSectionTitle: 'Reports to',
    DirectReportsSectionTitle: 'Direct Reports',
    OrganizationSectionTitle: 'Organization',
    YouWorkWithSubSectionTitle: 'You work with',
    UserWorksWithSubSectionTitle: 'Works with',
    // LocalizationHelper - Person card profile component
    SkillsAndExperienceSectionTitle: 'Skills & Experience',
    AboutCompactSectionTitle: 'About',
    SkillsSubSectionTitle: 'Skills',
    LanguagesSubSectionTitle: 'Languages',
    WorkExperienceSubSectionTitle: 'Work Experience',
    EducationSubSectionTitle: 'Education',
    ProfessionalInterestsSubSectionTitle: 'Professional Interests',
    PersonalInterestsSubSectionTitle: 'Personal Interests',
    BirthdaySubSectionTitle: 'Birthday',
    CurrentYearSubtitle: 'Current',
    // LocalizationHelper - Person card files component
    FilesSectionTitle: 'Files',
    SharedTextSubtitle: 'Shared',

    UserProperties: 'User properties',
    PageProperties: 'Page properties',

    UserString: 'User',
    PageString: 'Page',

    TextIconTitleCompletion: 'Phrase completion',
    TextIconTitleSynonym: 'Synonym',
    TextIconTitleQandA: 'Q&A',
    TextHeaderSuggestionSectionQandA: 'Azure OpenAI Q&A',
    TextHeaderSuggestionSectionSynonyms: 'Azure OpenAI synonyms and completions',
    TextHeaderPanelOpenAiQandA: 'Azure OpenAI - Q&A',
    TextQueryTemplateJobTitleToOpenAi: 'As "{JOBTITLE}", Suggest {NUMBER} questions to ask about "{TEXT}". Output formt: 1.xxx 2.xxx',
    TextQueryTemplateSynonymsToOpenAi: 'Suggest {NUMBER} synonyms for "{TEXT}". Output formt: 1.xxx 2.xxx',
    TextQueryTemplateCompletionsToOpenAi: 'Suggest {NUMBER} short phrase completions for "{TEXT}". Output formt: 1.xxx 2.xxx',
    TextCopyToClipboard: 'Copy to clipboard',
    TextSuggestAnotherAnswer: 'Suggest another answer',
    TextSubmit: 'Submit',
    TextUndeterminedError: 'Undetermined error',
    TextErrorInitialResponseEmpty: 'Response from AI was empty or had incorrect output format',
    TextAdvancedTextModel: 'Try the most capable AI model "text-davinci-003"',
    TextBestGuess: 'The best guess',
    TextBetaDisclaimer: 'This is a Beta feature. If you have any feedback, please log a ticket.',

    //KPMG Specific strings
    MissingTermsText: 'The following term(s) are no longer available, please update your selection:',
    ProfileHomeInstanceMessage: 'Intranet Home Site',
    ProfileHomeInstanceDescMessage: 'Your home site defines where you can set your profile properties.',
    ProfileHomeCurrentInstanceMessage: 'Set this current site as your home intranet',
    ProfileHomeAlternativeInstanceMessage: 'Alternatively, update the url below',
    ProfileInstructionMessage: 'Viewing / Editing your profile can only be done from your One Intranet home site.',
    ProfileInstructionActionMessage: 'Go to your current One Intranet home site',
    ProfileHomeInstanceDescMessageInfoPanel: 'Your home site defines where you can set your profile properties. This is typically the One Intranet site for the country you reside in.',
    ManagedMetaDataFieldTooManyItemsErrorMessage: 'You currently have too many items selected. Please remove items with red text to start to see results in the One Intranet webparts.',
    //Download dialog strings
    ProgressBarLabel: 'Getting data...',
    ItemsFoundMessage: '{{num}} items found.',
    DataReadyMessage: 'The report is ready for download.',
    DialogTitle: 'Report download',
    DialogCloseLabel: 'Close dialog',
    LikesWarning: 'Adding likes and comments count to the report will slow down the download. Do you want to omit these columns',
    LikesToggleLabel: 'Omit likes and comments count?',
    LikesToggleOn: 'Omit them',
    LikesToggleOff: 'Keep them',
    GenerateButton: 'Start report generation',
    DownloadButton: 'Download',
    IncompleteDataSetMessage: 'There was an issue retrieving the complete data set from SharePoint. The downloaded file will include {{0}} of {{1}} items.',
    InitialSearchResultsHiddenPlaceholder: 'Please use the search controls above to see the relevant information',
  };
});
