define([], function () {
  return {
    //generic
    OpenButton: "Open",
    CloseButton: "Close",
    CancelButton: "Cancel",
    EditButton: "Edit",
    CloneButton: "Copy",
    CreateButton: "Create",
    DeleteButton: "Delete",
    ChooseButton: "Choose",
    TestButton: "Test",
    ConfigureButton: "Configure",
    ProceedButton: "Proceed",
    DeleteConfirmation: "Are you sure you wish to delete this item?",
    FollowButton: "Follow",
    CleanButton: "Clean",
    FilterButton: "Filter",
    SelectedItemsText: "Selected items",
    AllItemsText: "All items",
    UnfollowButton: "Stop following",
    FollowingHeader: "Following",
    ShareButton: "Share",
    SettingsButton: "Settings",
    TermPickerTitle: "Select a term",
    ToggleOnAriaLabel: "This toggle is checked. Press to uncheck.",
    ToggleOffAriaLabel: "This toggle is unchecked. Press to check.",
    ToggleYesText: "Yes",
    ToggleNoText: "No",
    ToggleOnText: "On",
    ToggleOffText: "Off",
    PreviewLabel: "Preview",
    RequestButton: "Request",
    SaveChangesButton: "Save changes",
    SaveButton: "Save",
    SelectButton: "Select",
    SaveForLaterButton: "Pin",
    RemoveSaveForLaterButton: "Remove from pinned",
    ResetButton: "Reset",
    ReadMoreLink: "Read more",
    DocumentLabel: "Document",
    WordLabel: "Word document",
    PowerPointLabel: "PowerPoint document",
    ExcelLabel: "Excel document",
    PdfLabel: "PDF document",
    VisioLabel: "Visio document",
    ImageLabel: "Images",
    VideoLabel: "Videos",
    TemplatesLabel: "Templates",
    GeneralTypesHeader: "General types",
    SpecificExtensionHeader: "Specific extensions",
    AllTextDocumentsOption: "All text documents (Word, PDF, Excel...)",
    AllDocumentsOption: "All documents (including images, videos and templates)",
    DefaultImagesOption: "Common image types (PNG, JPG and GIF)",
    PageLabel: "Page",
    SendEmailButton: "Email",
    ChatButton: "Chat",
    ViewProfileButton: "View profile",
    CheckedOutTo: "Checked out to",
    StartDate: "Start date",
    StartTime: "Start time",
    Location: "Location",
    DueDate: "Due date",
    OpenInNewWindowButton: "Open in new tab",
    penLinkAria: "Open link",
    EmptyOption: "(None)",
    TextFormFieldPlaceholder: "Enter text here",
    DateFormFieldPlaceholder: "Enter a date",
    NumberFormFieldPlaceholder: "Enter value here",
    UnsupportedFieldType: "Unsupported field type",
    InvalidNumberValue: "The value should be a number, actual is",
    LoadingLabel: "Loading...",
    DropdownPlaceholder: "Select an option",
    SeeMoreButton: "See more",
    SeeLessButton: "See less",
    LoadMoreButton: "Load more",
    MoreInformation: "More information",
    OpenSiteButton: "View site",
    OpenLibraryButton: "View library",
    DownloadImageButton: "Download image",
    DownloadButton: "Download",
    TranscriptLink: "Transcript",

    NoAssignedLabel: "No assigned",
    ShareButton: "Share",
    LikeButton: "Like",
    UnlikeButton: "Unlike",
    LikeCountLabel: "likes",
    ShareYammerButton: "Yam this",
    ShareTeamsButton: "Chat in Teams",
    CopyUrlButton: "Copy link",

    NoResultsMessage: "No items available",
    SearchLabel: "Search",
    PreviousButton: "Previous",
    NextButton: "Next",
    UpButton: 'Move item up',
    DownButton: 'Move item down',

    MaximumItemsReached: "The maximum number of items has been reached",

    PaginationLabel: "Pagination",
    PaginationGotoLabel: "Go to page {{n}}",
    PaginationCurrentLabel: "Current page",

    SortLabel: "Sort",

    // calendar response status
    EventAccepted: "You have accepted",
    EventDeclined: "You have declined",
    EventNone: "You are not an attendee",
    EventNotResponded: "You have not responded",
    EventOrganizer: "You are the organizer",
    EventTentativelyAccepted: "You have tentatively accepted",

    //Sorting
    SortingDateAscOption: "Older to newer",
    SortingDateDesOption: "Newer to older",

    SortingNumberAscOption: "Smaller to larger",
    SortingNumberDesOption: "Larger to smaller",

    SortingStringAscOption: "A to Z",
    SortingStringDesOption: "Z to A",
    
    // time
    HoursLabel: "Hours",
    MinutesLabel: "Minutes",
    
    //Validation messages
    ValidationExtensionMessage: 'This file extension is not allowed',
    ValidationSortListMessage: 'This is not a valid sort list',
    ValidationGuidMessage: 'This is not a valid guid',
    ValidationNumberMessage: 'This is not a valid number',
    ValidationUrlMessage: 'This is not a valid url',
    ValidationRequiredMessage: 'This field is required',
    ValidationCodeMessage: 'This is not a valid code',

    // Dates
    MonthJanuary: 'January',
    MonthFebruary: 'February',
    MonthMarch: 'March',
    MonthApril: 'April',
    MonthMay: 'May',
    MonthJune: 'June',
    MonthJuly: 'July',
    MonthAugust: 'August',
    MonthSeptember: 'September',
    MonthOctober: 'October',
    MonthNovember: 'November',
    MonthDecember: 'December',
    ShortMonthJanuary: 'Jan',
    ShortMonthFebruary: 'Feb',
    ShortMonthMarch: 'Mar',
    ShortMonthApril: 'Apr',
    ShortMonthMay: 'May',
    ShortMonthJune: 'Jun',
    ShortMonthJuly: 'Jul',
    ShortMonthAugust: 'Aug',
    ShortMonthSeptember: 'Sep',
    ShortMonthOctober: 'Oct',
    ShortMonthNovember: 'Nov',
    ShortMonthDecember: 'Dec',
    DaySunday: 'Sunday',
    DayMonday: 'Monday',
    DayTuesday: 'Tuesday',
    DayWednesday: 'Wednesday',
    DayThursday: 'Thursday',
    DayFriday: 'Friday',
    DaySaturday: 'Saturday',
    ShortDaySunday: 'S',
    ShortDayMonday: 'M',
    ShortDayTuesday: 'T',
    ShortDayWednesday: 'W',
    ShortDayThursday: 'T',
    ShortDayFriday: 'F',
    ShortDaySaturday: 'S',
    DatePickerGoToToday: 'Go to today',
    DatePickerPrevMonthAriaLabel: 'Go to previous month',
    DatePickerNextMonthAriaLabel: 'Go to next month',
    DatePickerPrevYearAriaLabel: 'Go to previous year',
    DatePickerNextYearAriaLabel: 'Go to next year',
    DateHelperIsRequiredErrorMessage: 'This date is required.',
    DateHelperInvalidInputErrorMessage: 'Invalid date format.',

    DatePickerFromDatePlaceholder: 'Start date',
    DatePickerToDatePlaceholder: 'End date',

    DateHelperTodayLabel: 'Today',
    DateHelperYesterdayLabel: 'Yesterday',
    DateHelperTomorrowLabel: 'Tomorrow',
    DateHelperInHoursLabel: 'In {{time}} hours',
    DateHelperInMinutesLabel: 'In {{time}} minutes',
    DateHelperInLess5MinutesLabel: 'In less than 5 minutes',
    DateHelperDaysAgoLabel: '{{days}} days ago',
    DateHelperHoursAgoLabel: '{{time}} hours ago',
    DateHelperMinutesAgoLabel: '{{time}} minutes ago',
    DateHelperLess5MinutesAgoLabel: 'Less than 5 minutes ago',
    DateHelperTimePrepositionLabel: 'at',
    DateHelperDatePrepositionLabel: 'on',
  }
});
